#Requires -Version 5.1
<#
.SYNOPSIS
  One-time setup: llama.cpp (optional), Python venv, Canis CLI, model folders.

.PARAMETER InstallLlama
  Install llama-server into LLAMA_DIR (GitHub release zip, or winget).

.PARAMETER InstallLlamaVia
  github | winget | auto  (auto = GitHub, then winget on failure)

.PARAMETER DownloadModels
  Run `hf download` when HF_BASE_GGUF_* / HF_ADAPTER_REPO are set in canis_env.bat

.EXAMPLE
  .\setup-canis-edge.ps1 -InstallLlama -InstallLlamaVia winget
#>
param(
  [switch]$InstallLlama,
  [ValidateSet("github", "winget", "auto")]
  [string]$InstallLlamaVia = "auto",
  [switch]$DownloadModels
)

function Resolve-LlamaInstallDir {
  param([string]$Preferred)
  $candidates = @(
    $Preferred,
    "$env:USERPROFILE\llama.cpp-gemma4",
    "C:\llama.cpp-gemma4"
  ) | Where-Object { $_ -and $_.Trim() } | Select-Object -Unique
  foreach ($dir in $candidates) {
    if (Test-Path (Join-Path $dir "llama-server.exe")) { return $dir }
  }
  $cmd = Get-Command llama-server.exe -ErrorAction SilentlyContinue
  if ($cmd) { return (Split-Path $cmd.Source -Parent) }
  if ($Preferred) { return $Preferred }
  return "$env:USERPROFILE\llama.cpp-gemma4"
}

function Write-CanisEnvBat {
  param([string]$CliRoot, [string]$LlamaDir)
  $path = Join-Path $CliRoot "canis_env.bat"
  $content = @"
@echo off
REM Generated by setup-canis-edge.ps1 — edit paths if your layout differs

set "LLAMA_DIR=$LlamaDir"
set "CANIS_MODELS_DIR=%LLAMA_DIR%\canis-models"
set "CANIS_TEACH_GEMMA=%USERPROFILE%\canis.teach\GEMMA"
set "MODEL_REL=canis-models/gemma-4-E2B-it-Q4_K_M.gguf"
set "ADAPTERS_DIR=%CANIS_MODELS_DIR%\lora"
set "CANIS_TEACH_ADAPTER=teach"
set "CANIS_DEFAULT_ADAPTER=teach"
set "CTX_SIZE=8192"
set "N_GPU_LAYERS=99"
set "HF_BASE_GGUF_REPO=unsloth/gemma-4-E2B-it-GGUF"
set "HF_BASE_GGUF_FILE=gemma-4-E2B-it-Q4_K_M.gguf"
set "HF_ADAPTER_REPO=CanisAI/teach-multilingual-gemma-4-e2b-r3"
set "HF_ADAPTER_GGUF_FILE=teach-multilingual-gemma-4-e2b-r3-Q4_K_M.gguf"
"@
  Set-Content -LiteralPath $path -Value $content -Encoding ASCII
  Write-Host "[OK] Wrote $path (LLAMA_DIR=$LlamaDir)"
}

function Copy-LlamaBinDirTo {
  param([string]$BinDir, [string]$LlamaDir)
  if (-not (Test-Path $BinDir)) { throw "Binary folder not found: $BinDir" }
  Get-ChildItem -Path $BinDir -File | ForEach-Object {
    Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $LlamaDir $_.Name) -Force
  }
}

function Install-LlamaFromZip {
  param([string]$LlamaDir, $Asset)
  $mb = [math]::Round($Asset.size / 1MB, 1)
  Write-Host "      Asset: $($Asset.name) (~${mb} MB)"

  $zip = Join-Path $env:TEMP $Asset.name
  if (Test-Path $zip) { Remove-Item $zip -Force }
  Invoke-WebRequest -Uri $Asset.browser_download_url -OutFile $zip -UseBasicParsing

  $extractRoot = Join-Path $LlamaDir "_install_extract"
  if (Test-Path $extractRoot) { Remove-Item $extractRoot -Recurse -Force }
  New-Item -ItemType Directory -Force -Path $extractRoot | Out-Null
  Expand-Archive -Path $zip -DestinationPath $extractRoot -Force
  Remove-Item $zip -ErrorAction SilentlyContinue

  $exe = Get-ChildItem -Path $extractRoot -Recurse -Filter "llama-server.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
  if (-not $exe) {
    Remove-Item $extractRoot -Recurse -Force -ErrorAction SilentlyContinue
    throw "llama-server.exe not found inside $($Asset.name)."
  }

  Write-Host "      Installing binaries from $($exe.DirectoryName) ..."
  Copy-LlamaBinDirTo -BinDir $exe.DirectoryName -LlamaDir $LlamaDir
  Remove-Item $extractRoot -Recurse -Force -ErrorAction SilentlyContinue
}

function Select-LlamaWindowsAsset {
  param($Assets)
  $list = @($Assets)
  $patterns = @(
    "llama-*-bin-win-cuda-12.4-x64.zip",
    "llama-*-bin-win-cuda-13.*-x64.zip",
    "llama-*-bin-win-cpu-x64.zip",
    "llama-*-bin-win-vulkan-x64.zip"
  )
  foreach ($pat in $patterns) {
    $hit = $list | Where-Object { $_.name -like $pat -and $_.name -notlike "cudart*" } | Select-Object -First 1
    if ($hit) { return $hit }
  }
  return $null
}

function Install-LlamaFromGitHub {
  param([string]$LlamaDir)
  Write-Host "[1/3] Downloading llama.cpp from GitHub (several minutes for large CUDA zip)..."
  $release = Invoke-RestMethod -Uri "https://api.github.com/repos/ggml-org/llama.cpp/releases/latest"
  Write-Host "      Release: $($release.tag_name)"
  $asset = Select-LlamaWindowsAsset -Assets $release.assets
  if (-not $asset) {
    throw "No matching Windows zip in release. Install manually or use -InstallLlamaVia winget."
  }
  Install-LlamaFromZip -LlamaDir $LlamaDir -Asset $asset
}

function Install-LlamaFromWinget {
  param([string]$LlamaDir)
  if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    throw "winget not found. Install App Installer from Microsoft Store, or use -InstallLlamaVia github."
  }
  Write-Host "[1/3] Installing llama.cpp via winget (ggml.llamacpp)..."
  winget install -e --id ggml.llamacpp --accept-package-agreements --accept-source-agreements
  if ($LASTEXITCODE -ne 0) { throw "winget install failed (exit $LASTEXITCODE)." }

  $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
    [System.Environment]::GetEnvironmentVariable("Path", "User")

  $binDir = $null
  $cmd = Get-Command llama-server.exe -ErrorAction SilentlyContinue
  if ($cmd) { $binDir = Split-Path $cmd.Source -Parent }

  if (-not $binDir) {
    $roots = @(
      "$env:LOCALAPPDATA\Microsoft\WinGet\Packages",
      "$env:LOCALAPPDATA\Programs",
      "$env:ProgramFiles"
    )
    foreach ($root in $roots) {
      if (-not (Test-Path $root)) { continue }
      $found = Get-ChildItem -Path $root -Recurse -Filter "llama-server.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
      if ($found) { $binDir = $found.DirectoryName; break }
    }
  }

  if (-not $binDir) {
    throw "winget finished but llama-server.exe not found. Open a new terminal and run: where llama-server"
  }

  Write-Host "      Copying from $binDir to $LlamaDir ..."
  Copy-LlamaBinDirTo -BinDir $binDir -LlamaDir $LlamaDir
  Write-Host "      Note: winget may install Vulkan build; for NVIDIA CUDA use GitHub cuda zip or a CUDA winget build when available."
}

$ErrorActionPreference = "Stop"
$CliRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $CliRoot

$preferredLlama = "$env:USERPROFILE\llama.cpp-gemma4"
if (Test-Path "$CliRoot\canis_env.bat") {
  & "$CliRoot\canis_env.bat"
  if ($env:LLAMA_DIR) { $preferredLlama = $env:LLAMA_DIR }
} else {
  $env:LLAMA_DIR = $preferredLlama
  $env:CANIS_MODELS_DIR = "$env:LLAMA_DIR\canis-models"
  $env:CANIS_TEACH_GEMMA = "$env:USERPROFILE\canis.teach\GEMMA"
  $env:HF_BASE_GGUF_REPO = "unsloth/gemma-4-E2B-it-GGUF"
  $env:HF_BASE_GGUF_FILE = "gemma-4-E2B-it-Q4_K_M.gguf"
  $env:HF_ADAPTER_REPO = "CanisAI/teach-multilingual-gemma-4-e2b-r3"
  $env:HF_ADAPTER_GGUF_FILE = "teach-multilingual-gemma-4-e2b-r3-Q4_K_M.gguf"
}
$env:LLAMA_DIR = Resolve-LlamaInstallDir -Preferred $preferredLlama
$env:CANIS_MODELS_DIR = "$($env:LLAMA_DIR)\canis-models"
if (-not $env:CANIS_TEACH_GEMMA) {
  $env:CANIS_TEACH_GEMMA = "$env:USERPROFILE\canis.teach\GEMMA"
}

Write-Host ""
Write-Host "================================================================"
Write-Host "  Canis Edge Setup (Windows)"
Write-Host "================================================================"
Write-Host ""

# --- llama.cpp ---
if ($InstallLlama) {
  $llamaDir = $env:LLAMA_DIR
  if (-not $llamaDir) { $llamaDir = "$env:USERPROFILE\llama.cpp-gemma4" }
  New-Item -ItemType Directory -Force -Path $llamaDir | Out-Null

  if (Test-Path "$llamaDir\llama-server.exe") {
    Write-Host "[OK] llama-server.exe already at $llamaDir"
  } else {
    $installed = $false
    if ($InstallLlamaVia -eq "winget") {
      Install-LlamaFromWinget -LlamaDir $llamaDir
      $installed = $true
    } elseif ($InstallLlamaVia -eq "github") {
      Install-LlamaFromGitHub -LlamaDir $llamaDir
      $installed = $true
    } else {
      try {
        Install-LlamaFromGitHub -LlamaDir $llamaDir
        $installed = $true
      } catch {
        Write-Host "[WARN] GitHub install failed: $($_.Exception.Message)"
        Write-Host "[INFO] Trying winget..."
        Install-LlamaFromWinget -LlamaDir $llamaDir
        $installed = $true
      }
    }
    if (-not $installed -or -not (Test-Path "$llamaDir\llama-server.exe")) {
      throw "llama-server.exe not found after install. Set LLAMA_DIR in canis_env.bat."
    }
    Write-Host "[OK] llama-server -> $llamaDir\llama-server.exe"
  }
  $env:LLAMA_DIR = Resolve-LlamaInstallDir -Preferred $llamaDir
} else {
  Write-Host "[SKIP] llama install (use -InstallLlama or install manually - see EDGE_SETUP.md)"
}

# --- folders ---
$edgeRoot = $env:CANIS_EDGE_ROOT
if (-not $edgeRoot) { $edgeRoot = "$env:USERPROFILE\canis.edge" }
foreach ($sub in @("models", "adapters")) {
  New-Item -ItemType Directory -Force -Path (Join-Path $edgeRoot $sub) | Out-Null
}
Write-Host "[OK] Data dirs: $edgeRoot"

# --- Python venv ---
Write-Host "[2/3] Python venv + Canis CLI..."
if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
  throw "Python 3.10+ not found on PATH."
}
if (-not (Test-Path ".\.venv\Scripts\python.exe")) {
  python -m venv .venv
}
.\.venv\Scripts\python.exe -m pip install -q --upgrade pip
.\.venv\Scripts\pip.exe install -q -e .
if (Test-Path ".\canis\requirements.txt") {
  .\.venv\Scripts\pip.exe install -q -r ".\canis\requirements.txt"
}

# --- optional HF download ---
if ($DownloadModels) {
  Write-Host "[3/3] Hugging Face downloads..."
  $hf = Get-Command hf -ErrorAction SilentlyContinue
  if (-not $hf) {
    .\.venv\Scripts\pip.exe install -q huggingface_hub
    $hfCmd = ".\.venv\Scripts\hf.exe"
  } else { $hfCmd = "hf" }

  $teachGemma = if ($env:CANIS_TEACH_GEMMA) { $env:CANIS_TEACH_GEMMA } else { Join-Path $env:USERPROFILE "canis.teach\GEMMA" }
  New-Item -ItemType Directory -Force -Path $teachGemma | Out-Null

  if ($env:HF_BASE_GGUF_REPO -and $env:HF_BASE_GGUF_FILE) {
    & $hfCmd download $env:HF_BASE_GGUF_REPO $env:HF_BASE_GGUF_FILE --local-dir $teachGemma
    Write-Host "      Base -> $teachGemma\$($env:HF_BASE_GGUF_FILE)"
  } else {
    Write-Host "      Set HF_BASE_GGUF_REPO + HF_BASE_GGUF_FILE in canis_env.bat"
  }

  if ($env:HF_ADAPTER_REPO -and $env:HF_ADAPTER_GGUF_FILE) {
    & $hfCmd download $env:HF_ADAPTER_REPO $env:HF_ADAPTER_GGUF_FILE --local-dir $teachGemma
    Write-Host "      LoRA -> $teachGemma\$($env:HF_ADAPTER_GGUF_FILE)"
  } elseif ($env:HF_ADAPTER_REPO) {
    Write-Host "      Set HF_ADAPTER_GGUF_FILE=teach-multilingual-gemma-4-e2b-r3-Q4_K_M.gguf in canis_env.bat"
  }

  powershell -NoProfile -ExecutionPolicy Bypass -File "$CliRoot\scripts\sync_canis_models_to_llama.ps1"
} else {
  Write-Host "[SKIP] model download (use -DownloadModels after editing canis_env.bat)"
}

$resolvedLlama = Resolve-LlamaInstallDir -Preferred $env:LLAMA_DIR
$env:LLAMA_DIR = $resolvedLlama
$env:CANIS_MODELS_DIR = "$resolvedLlama\canis-models"
Write-CanisEnvBat -CliRoot $CliRoot -LlamaDir $resolvedLlama

Write-Host ""
Write-Host "================================================================"
Write-Host "  Models linked under:"
Write-Host "    $($env:CANIS_MODELS_DIR)"
Write-Host "  LoRA folders:"
Write-Host "    $($env:CANIS_MODELS_DIR)\lora"
Write-Host ""
Write-Host "  Then run:  .\run_edge.bat"
Write-Host ""
$apiPort = if ($env:CANIS_API_PORT) { $env:CANIS_API_PORT } else { "5000" }
Write-Host "  Studio URL to paste:  http://localhost:$apiPort"
Write-Host "  Live demo:            https://canis.appwrite.network"
Write-Host "================================================================"
